version = 0.1

[default.build.parameters]
template_file = "infra/template.yaml"

[default.validate.parameters]
template_file = "infra/template.yaml"
lint = true

[dev.deploy.parameters]
stack_name = "hawkerflow-dev"
resolve_s3 = true
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "hawkerflow-prod"
resolve_s3 = true
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
confirm_changeset = false
